# Generated by Django 3.1.5 on 2021-04-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Gender', models.CharField(choices=[['Male', 'Male'], ['Female', 'Female'], ['Other', 'Other']], max_length=50)),
                ('Customer_Income_group', models.IntegerField()),
                ('Customer_Region', models.CharField(choices=[['East', 'East'], ['West', 'West'], ['North', 'North'], ['South', 'South']], max_length=50)),
                ('Customer_Marital_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy_tbl',
            fields=[
                ('Policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_of_Purchase', models.DateField(blank=True)),
                ('Fuel', models.CharField(choices=[['CNG', 'CNG'], ['Petrol', 'Petrol'], ['Diesel', 'Diesel']], max_length=50)),
                ('Vehicle_Segment', models.CharField(max_length=1)),
                ('Premium', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='policy.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Policy_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodily_injury_liability', models.BooleanField()),
                ('personal_injury_protection', models.BooleanField()),
                ('property_damage_liability', models.BooleanField()),
                ('collision', models.BooleanField()),
                ('comprehensive', models.BooleanField()),
                ('Policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_id', to='policy.policy_tbl')),
            ],
        ),
    ]
