# Generated by Django 3.1.5 on 2021-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_Income_group',
            field=models.CharField(max_length=50),
        ),
    ]
